version: '3.7'
services:
  keycloak:
    image: jboss/keycloak:latest
    container_name: keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=h2
    ports:
      - "8080:8080"
    networks:
      - keycloak-net
    restart: always

networks:
  keycloak-net:
    driver: bridge
