spring:
  application:
     name: user
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/microservices
  config:
    import: optional:configserver:http://localhost:8888
